In [5]:
%load_ext autoreload
%autoreload 2
import os, sys
import pandas as pd
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [6]:
DATA_DIR = './data/auxiliary-data/'
stock_prices = os.path.join(DATA_DIR, 'sg-stock-prices.csv')
stock_prices_table = pd.read_csv(stock_prices)

In [16]:
stock_prices_table.head(10)

        name  symbol        date   open   high    low  close  adjusted_close
0  DBS Group  D05.SI  2021-01-04  25.13  25.34  25.01  25.34          22.833
1  DBS Group  D05.SI  2021-01-05  25.22  25.35  25.09  25.35          22.842
2  DBS Group  D05.SI  2021-01-06  25.30  25.35  25.07  25.18          22.689
3  DBS Group  D05.SI  2021-01-07  25.68  26.18  25.63  26.05          23.473
4  DBS Group  D05.SI  2021-01-08  26.55  27.47  26.50  27.42          24.707
5  DBS Group  D05.SI  2021-01-11  27.39  27.39  26.92  26.92          24.257
6  DBS Group  D05.SI  2021-01-12  26.79  26.86  26.52  26.73          24.086
7  DBS Group  D05.SI  2021-01-13  27.00  27.10  26.72  26.76          24.113
8  DBS Group  D05.SI  2021-01-14  26.90  26.99  26.77  26.99          24.320
9  DBS Group  D05.SI  2021-01-15  27.00  27.02  26.79  26.85          24.194

In [13]:
stock_prices_table.isnull().any()

name              False
symbol            False
date              False
open              False
high              False
low               False
close             False
adjusted_close    False
dtype: bool

In [18]:
stock_prices_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35498 entries, 0 to 35497
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            35498 non-null  object
 1   symbol          35498 non-null  object
 2   date            35498 non-null  object
 3   open            35498 non-null  float64
 4   high            35498 non-null  float64
 5   low             35498 non-null  float64
 6   close           35498 non-null  float64
 7   adjusted_close  35498 non-null  float64
dtypes: float64(5), object(3)
memory usage: 2.2+ MB